// This file is auto-generated by ts_compile() - do not edit manually.
// Source: plots.R

import { Robj } from 'rserve-ts';
import { z } from 'zod';


export const plots = Robj.ocap([], Robj.list(Robj.list({ id: Robj.character(1), title: Robj.character(1), structureJson: Robj.character(1) })));


export type TPlots = z.infer<typeof plots>;


export const plotsAppSchema = {
  plots
} satisfies z.ZodRawShape;

export type TPlotsApp = z.infer<z.ZodObject<typeof plotsAppSchema, "strip">>;

export default plotsAppSchema;
