inzPlotDefaults <-
function() {
  # Houses all of the default settings for plotting. Alternatively,
  # could edit them (i.e., points to a list in global environment)
    
    list(pch            = 1,
         col            = "red",
         col.pt         = "grey50",
         cex            = 1,
         cex.pt         = 0.6,
         cex.lab        = 1,
         cex.axis       = 0.8,
         cex.main       = 1.2,
         cex.text       = 1,
         bg             = "white",
         fill.pt        = "transparent",
         lwd            = 1,
         lty            = 1,
         lwd.pt         = 2,
         col.line       = "blue",
         col.sub        = "wheat",
         jitter         = "",
         trend          = NULL,
         smooth         = NULL,
         LOE            = NULL,
         join           = FALSE,
         col.trend      = list(linear = "blue",
                               quadratic = "red",
                               cubic ="green4"),
         col.smooth     = c("magenta"),
         col.LOE        = "black",
         lty.LOE        = 2,
         box            = TRUE,
         box.lwd        = c(2, 0.7),
         box.col        = "black",
         box.fill       = "grey90",
         bar.lwd        = 1,
         bar.col        = "black",
         bar.fill       = "darkgreen",
         inf.lwd.comp   = 4,
         inf.col.comp   = "black",
         inference.type = NULL,
         inference.par  = NULL,
         bs.inference   = FALSE)
}
