on: [push, pull_request]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release", cache: 1 }
          - { os: macOS-latest, r: "release", cache: 1 }
          - { os: ubuntu-latest, r: "release", cache: 1 }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ matrix.config.cache  }}
          needs: |
            check
            coverage
          install-pandoc: true

      - name: Test coverage
        run: covr::codecov()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: Rscript {0}
